spring.application.name=banvexe

spring.datasource.url=jdbc:h2:mem:banvexe
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
=======

spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false
# Cấu hình Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
>>>>>>> ddac1e8b8549e9a124128f28370698981e8d0673
payos.clientId=846e0e16-964f-4ebd-8538-ffc3007c052f
payos.apiKey=206daf4b-9bdb-4976-af92-72f0e46515e1