spring.application.name=banvexe

spring.datasource.url=jdbc:mysql://localhost:3306/banvexe
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false
# Cấu hình Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG